language: java
jdk:
  - oraclejdk8 # The Android Plugin for Gradle comes in .class files which require JDK 8.
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - sudo apt-get install -qq expect libstdc++6:i386 lib32z1
  - export COMPONENTS=build-tools-22.0.1,android-22,android-18,sys-img-armeabi-v7a-android-18,extra-google-m2repository,extra-android-m2repository,extra-android-support
  # The Android SDK License may be valid for the Travis run, and then terminates automatically.
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS --accept=android-sdk-license-c81a61d9
  - source ~/.android-sdk-installer/env
  - export TERM=dumb # to get clean gradle output

  # Create and start emulator
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window -memory 512 -wipe-data > emulator.log 2>&1 &
  - adb logcat > logcat.log &
  - wait_for_emulator

script:
  - ./gradlew --debug check
# - ./gradlew --debug uploadArchives
  - ./gradlew --stop
  - ./gradlew --debug integTest

after_failure:
  - cat emulator.log
  - cat logcat.log
